FROM node:lts as builder
COPY public /app/public
COPY src /app/src
COPY package.json /app/
COPY package-lock.json /app/
ENV NODE_ENV production
ENV REACT_APP_API_PREFIX https://raw.ninja:8080
WORKDIR /app
RUN npm ci --force
RUN npm run build

FROM nginx:1.25.3-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]