services:
  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - ./local.env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: