FROM golang:1.21.4-bullseye as build
RUN apt-get update && apt-get install -y libraw-dev
WORKDIR /app
COPY app ./app
COPY auth ./auth
COPY common ./common
COPY descriptor ./descriptor
COPY docs ./docs
COPY image ./image
COPY mail ./mail
COPY photo ./photo
COPY search ./search
COPY stats ./stats
COPY web/logging.go ./web/
COPY web/routes.go ./web/
COPY main.go .
COPY go.mod .
COPY go.sum .
RUN go build -v -o rawninja main.go

FROM debian:11.8-slim
RUN apt-get update && apt-get install -y libraw-dev
COPY --from=build /app/rawninja /usr/local/bin/rawninja
CMD [ "/usr/local/bin/rawninja" ] 
EXPOSE 8080