services:
  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - envfiles/postgres.env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  backend:
    image: rawninja-backend
    container_name: backend
    env_file:
      - envfiles/local.env
    ports:
      - 8080:8080
    links:
      - postgres
    volumes:
      - .:/etc/rawninja
  frontend:
    image: rawninja-frontend
    container_name: frontend
    env_file:
      - web/frontend/.env
    ports:
      - 3000:443
    links:
      - backend
    volumes:
      - ./certificates:/etc/rawninja/certificates