services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PORT=5432
      - POSTGRES_DB=photostorage
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
    ports:
      - 5432:5432
    volumes:
      - ./environments/local/postgres:/var/lib/postgresql/data
    networks:
      - public
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    image: rawninja-backend
    restart: always
    container_name: backend
    env_file:
      - ./environments/local/app.env
    ports:
      - 8080:8080
    links:
      - postgres
    volumes:
      - ./environments/local:/etc/rawninja
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - public
  frontend:
    image: rawninja-frontend
    restart: always
    container_name: frontend
    ports:
      - 80:80
    networks:
      - public

networks:
  public:
    driver: bridge