info:
  contact: {}
paths:
  /example/helloworld:
    get:
      consumes:
      - application/json
      description: do hello world
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: hello world example
      tags:
      - example
  /example/ping:
    get:
      consumes:
      - application/json
      description: do ping-pong
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
swagger: "2.0"
