name: backend

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Install dependencies
        working-directory: backend
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          sudo apt-get install libraw-dev

      - name: Init swagger
        working-directory: backend
        run: swag i

      - name: Build
        working-directory: backend
        run: go build -v main.go

      - name: Test
        working-directory: backend
        run: go test -v ./...