name: github.com/inokone/photostorage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Install dependencies
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest

      - name: Init swagger
        working-directory: ./src
        run: swag init

      - name: Build
        run: go build -v ./src/

      - name: Test
        run: go test -v ./src/