name: github.com/inokone/photostorage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Install dependencies
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          go install github.com/go-critic/go-critic/cmd/gocritic@latest
          sudo apt-get install libraw-dev

      - name: Init swagger
        run: swag i -d "./,./app,./auth,./common,./photo,./descriptor,./web,./statistics"

      - name: Build
        run: go build -v main.go

      - name: Test
        run: go test -v ./...

      - name: Static Code Analysis
        run: gocritic check ./...